// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDwaLkHD6iOIK3ImfbHXfKd_oDq8Y4qF0',
    appId: '1:733231722253:web:edf38040cb93371f71ca44',
    messagingSenderId: '733231722253',
    projectId: 'mat-security',
    authDomain: 'mat-security.firebaseapp.com',
    databaseURL: 'https://mat-security-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mat-security.appspot.com',
    measurementId: 'G-DEWSGZ8PWC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZI0QWIvWqwB1grw2DIN7Bp7CfnGrrfHc',
    appId: '1:733231722253:android:5ff550155774751f71ca44',
    messagingSenderId: '733231722253',
    projectId: 'mat-security',
    databaseURL: 'https://mat-security-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mat-security.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAm8srvk0UhCtFK6Zxi4H_GoMn5SP2Fbec',
    appId: '1:733231722253:ios:7bedb4ef8bd618a871ca44',
    messagingSenderId: '733231722253',
    projectId: 'mat-security',
    databaseURL: 'https://mat-security-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mat-security.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAm8srvk0UhCtFK6Zxi4H_GoMn5SP2Fbec',
    appId: '1:733231722253:ios:7bedb4ef8bd618a871ca44',
    messagingSenderId: '733231722253',
    projectId: 'mat-security',
    databaseURL: 'https://mat-security-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mat-security.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDwaLkHD6iOIK3ImfbHXfKd_oDq8Y4qF0',
    appId: '1:733231722253:web:e13281bd0b404c6a71ca44',
    messagingSenderId: '733231722253',
    projectId: 'mat-security',
    authDomain: 'mat-security.firebaseapp.com',
    databaseURL: 'https://mat-security-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mat-security.appspot.com',
    measurementId: 'G-RX1VJJEDBK',
  );

}